name: suggest_a_feature
description: Ready-made Flutter package for collecting suggestions from users.
version: 0.6.0
repository: https://github.com/flutterwtf/Suggest-a-Feature
homepage: https://pub.dev/packages/suggest_a_feature

topics:
  - suggestions
  - bug-reporting
  - feedback

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.0"

dependencies:
  equatable: ">=2.0.7 <4.0.0"
  flutter:
    sdk: flutter
  flutter_svg: ^2.3.0
  intl: ^0.20.2
  wtf_sliding_sheet: ^1.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.3.0

flutter:
  assets:
    - assets/
