// Mocks generated by Mockito 5.3.2 from annotations
// in suggest_a_feature/test/utils/shared_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:ui' as _i5;

import 'package:flutter/material.dart' as _i6;
import 'package:flutter_bloc/flutter_bloc.dart' as _i16;
import 'package:mockito/mockito.dart' as _i1;
import 'package:suggest_a_feature/src/data/interfaces/i_suggestions_data_source.dart'
    as _i18;
import 'package:suggest_a_feature/src/data/repositories/suggestion_repository.dart'
    as _i8;
import 'package:suggest_a_feature/src/domain/entities/comment.dart' as _i12;
import 'package:suggest_a_feature/src/domain/entities/suggestion.dart' as _i10;
import 'package:suggest_a_feature/src/domain/entities/suggestion_author.dart'
    as _i11;
import 'package:suggest_a_feature/src/domain/interactors/suggestion_interactor.dart'
    as _i13;
import 'package:suggest_a_feature/src/domain/utils/wrapper.dart' as _i2;
import 'package:suggest_a_feature/src/presentation/pages/suggestion/suggestion_cubit.dart'
    as _i14;
import 'package:suggest_a_feature/src/presentation/pages/suggestion/suggestion_state.dart'
    as _i3;
import 'package:suggest_a_feature/src/presentation/pages/suggestions/suggestions_cubit.dart'
    as _i17;
import 'package:suggest_a_feature/src/presentation/pages/suggestions/suggestions_state.dart'
    as _i4;
import 'package:suggest_a_feature/src/presentation/utils/typedefs.dart' as _i15;
import 'package:suggest_a_feature/suggest_a_feature.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWrapper_0<T> extends _i1.SmartFake implements _i2.Wrapper<T> {
  _FakeWrapper_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSuggestionState_1 extends _i1.SmartFake
    implements _i3.SuggestionState {
  _FakeSuggestionState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSuggestionsState_2 extends _i1.SmartFake
    implements _i4.SuggestionsState {
  _FakeSuggestionsState_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeColor_3 extends _i1.SmartFake implements _i5.Color {
  _FakeColor_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTextStyle_4 extends _i1.SmartFake implements _i6.TextStyle {
  _FakeTextStyle_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i6.DiagnosticLevel? minLevel = _i6.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeSuggestionsTheme_5 extends _i1.SmartFake
    implements _i7.SuggestionsTheme {
  _FakeSuggestionsTheme_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SuggestionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSuggestionRepository extends _i1.Mock
    implements _i8.SuggestionRepository {
  MockSuggestionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Stream<List<_i10.Suggestion>> get suggestionsStream =>
      (super.noSuchMethod(
        Invocation.getter(#suggestionsStream),
        returnValue: _i9.Stream<List<_i10.Suggestion>>.empty(),
      ) as _i9.Stream<List<_i10.Suggestion>>);
  @override
  List<_i10.Suggestion> get suggestions => (super.noSuchMethod(
        Invocation.getter(#suggestions),
        returnValue: <_i10.Suggestion>[],
      ) as List<_i10.Suggestion>);
  @override
  Map<String, _i11.SuggestionAuthor?> get userInfo => (super.noSuchMethod(
        Invocation.getter(#userInfo),
        returnValue: <String, _i11.SuggestionAuthor?>{},
      ) as Map<String, _i11.SuggestionAuthor?>);
  @override
  void refreshSuggestions(
    _i10.Suggestion? suggestion, {
    bool? saveComments = true,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #refreshSuggestions,
          [suggestion],
          {#saveComments: saveComments},
        ),
        returnValueForMissingStub: null,
      );
  @override
  void initSuggestions() => super.noSuchMethod(
        Invocation.method(
          #initSuggestions,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i9.Future<_i2.Wrapper<_i10.Suggestion>> getSuggestionById(
          String? suggestionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSuggestionById,
          [suggestionId],
        ),
        returnValue: _i9.Future<_i2.Wrapper<_i10.Suggestion>>.value(
            _FakeWrapper_0<_i10.Suggestion>(
          this,
          Invocation.method(
            #getSuggestionById,
            [suggestionId],
          ),
        )),
      ) as _i9.Future<_i2.Wrapper<_i10.Suggestion>>);
  @override
  _i9.Future<_i2.Wrapper<_i10.Suggestion>> createSuggestion(
          _i10.CreateSuggestionModel? suggestion) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSuggestion,
          [suggestion],
        ),
        returnValue: _i9.Future<_i2.Wrapper<_i10.Suggestion>>.value(
            _FakeWrapper_0<_i10.Suggestion>(
          this,
          Invocation.method(
            #createSuggestion,
            [suggestion],
          ),
        )),
      ) as _i9.Future<_i2.Wrapper<_i10.Suggestion>>);
  @override
  _i9.Future<_i2.Wrapper<_i10.Suggestion>> updateSuggestion(
          _i10.Suggestion? suggestion) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSuggestion,
          [suggestion],
        ),
        returnValue: _i9.Future<_i2.Wrapper<_i10.Suggestion>>.value(
            _FakeWrapper_0<_i10.Suggestion>(
          this,
          Invocation.method(
            #updateSuggestion,
            [suggestion],
          ),
        )),
      ) as _i9.Future<_i2.Wrapper<_i10.Suggestion>>);
  @override
  _i9.Future<void> deleteSuggestion(String? suggestionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteSuggestion,
          [suggestionId],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
  @override
  _i9.Future<void> addNotifyToUpdateUser(String? suggestionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #addNotifyToUpdateUser,
          [suggestionId],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
  @override
  _i9.Future<void> deleteNotifyToUpdateUser(String? suggestionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteNotifyToUpdateUser,
          [suggestionId],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
  @override
  void downvote(String? suggestionId) => super.noSuchMethod(
        Invocation.method(
          #downvote,
          [suggestionId],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void upvote(String? suggestionId) => super.noSuchMethod(
        Invocation.method(
          #upvote,
          [suggestionId],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i9.Future<_i2.Wrapper<List<_i12.Comment>>> getAllComments(
          String? suggestionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllComments,
          [suggestionId],
        ),
        returnValue: _i9.Future<_i2.Wrapper<List<_i12.Comment>>>.value(
            _FakeWrapper_0<List<_i12.Comment>>(
          this,
          Invocation.method(
            #getAllComments,
            [suggestionId],
          ),
        )),
      ) as _i9.Future<_i2.Wrapper<List<_i12.Comment>>>);
  @override
  _i9.Future<_i2.Wrapper<_i12.Comment>> createComment(
          _i12.CreateCommentModel? comment) =>
      (super.noSuchMethod(
        Invocation.method(
          #createComment,
          [comment],
        ),
        returnValue: _i9.Future<_i2.Wrapper<_i12.Comment>>.value(
            _FakeWrapper_0<_i12.Comment>(
          this,
          Invocation.method(
            #createComment,
            [comment],
          ),
        )),
      ) as _i9.Future<_i2.Wrapper<_i12.Comment>>);
}

/// A class which mocks [SuggestionInteractor].
///
/// See the documentation for Mockito's code generation for more information.
class MockSuggestionInteractor extends _i1.Mock
    implements _i13.SuggestionInteractor {
  MockSuggestionInteractor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Stream<List<_i10.Suggestion>> get suggestionsStream =>
      (super.noSuchMethod(
        Invocation.getter(#suggestionsStream),
        returnValue: _i9.Stream<List<_i10.Suggestion>>.empty(),
      ) as _i9.Stream<List<_i10.Suggestion>>);
  @override
  Map<String, _i11.SuggestionAuthor?> get userInfo => (super.noSuchMethod(
        Invocation.getter(#userInfo),
        returnValue: <String, _i11.SuggestionAuthor?>{},
      ) as Map<String, _i11.SuggestionAuthor?>);
  @override
  void initSuggestions() => super.noSuchMethod(
        Invocation.method(
          #initSuggestions,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i9.Future<_i2.Wrapper<_i10.Suggestion>> createSuggestion(
          _i10.CreateSuggestionModel? suggestion) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSuggestion,
          [suggestion],
        ),
        returnValue: _i9.Future<_i2.Wrapper<_i10.Suggestion>>.value(
            _FakeWrapper_0<_i10.Suggestion>(
          this,
          Invocation.method(
            #createSuggestion,
            [suggestion],
          ),
        )),
      ) as _i9.Future<_i2.Wrapper<_i10.Suggestion>>);
  @override
  _i9.Future<_i2.Wrapper<_i10.Suggestion>> updateSuggestion(
          _i10.Suggestion? suggestion) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSuggestion,
          [suggestion],
        ),
        returnValue: _i9.Future<_i2.Wrapper<_i10.Suggestion>>.value(
            _FakeWrapper_0<_i10.Suggestion>(
          this,
          Invocation.method(
            #updateSuggestion,
            [suggestion],
          ),
        )),
      ) as _i9.Future<_i2.Wrapper<_i10.Suggestion>>);
  @override
  _i9.Future<void> deleteSuggestion(String? suggestionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteSuggestion,
          [suggestionId],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
  @override
  void upvote(String? suggestionId) => super.noSuchMethod(
        Invocation.method(
          #upvote,
          [suggestionId],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void downvote(String? suggestionId) => super.noSuchMethod(
        Invocation.method(
          #downvote,
          [suggestionId],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i9.Future<void> addNotifyToUpdateUser(String? suggestionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #addNotifyToUpdateUser,
          [suggestionId],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
  @override
  _i9.Future<void> deleteNotifyToUpdateUser(String? suggestionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteNotifyToUpdateUser,
          [suggestionId],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
  @override
  void refreshSuggestions(
    _i10.Suggestion? suggestion, {
    bool? saveComments = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #refreshSuggestions,
          [suggestion],
          {#saveComments: saveComments},
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i9.Future<_i2.Wrapper<List<_i12.Comment>>> getAllComments(
          String? suggestionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllComments,
          [suggestionId],
        ),
        returnValue: _i9.Future<_i2.Wrapper<List<_i12.Comment>>>.value(
            _FakeWrapper_0<List<_i12.Comment>>(
          this,
          Invocation.method(
            #getAllComments,
            [suggestionId],
          ),
        )),
      ) as _i9.Future<_i2.Wrapper<List<_i12.Comment>>>);
  @override
  _i9.Future<_i2.Wrapper<_i12.Comment>> createComment(
          _i12.CreateCommentModel? comment) =>
      (super.noSuchMethod(
        Invocation.method(
          #createComment,
          [comment],
        ),
        returnValue: _i9.Future<_i2.Wrapper<_i12.Comment>>.value(
            _FakeWrapper_0<_i12.Comment>(
          this,
          Invocation.method(
            #createComment,
            [comment],
          ),
        )),
      ) as _i9.Future<_i2.Wrapper<_i12.Comment>>);
}

/// A class which mocks [SuggestionCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockSuggestionCubit extends _i1.Mock implements _i14.SuggestionCubit {
  MockSuggestionCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.SuggestionState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeSuggestionState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.SuggestionState);
  @override
  _i9.Stream<_i3.SuggestionState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i9.Stream<_i3.SuggestionState>.empty(),
      ) as _i9.Stream<_i3.SuggestionState>);
  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);
  @override
  void init(
    _i10.Suggestion? suggestion,
    _i15.OnGetUserById? getUserById,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #init,
          [
            suggestion,
            getUserById,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void reset() => super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void openCreateEditBottomSheet() => super.noSuchMethod(
        Invocation.method(
          #openCreateEditBottomSheet,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void openConfirmationBottomSheet() => super.noSuchMethod(
        Invocation.method(
          #openConfirmationBottomSheet,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void openEditDeleteBottomSheet() => super.noSuchMethod(
        Invocation.method(
          #openEditDeleteBottomSheet,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void openNotificationBottomSheet() => super.noSuchMethod(
        Invocation.method(
          #openNotificationBottomSheet,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void openCreateCommentBottomSheet() => super.noSuchMethod(
        Invocation.method(
          #openCreateCommentBottomSheet,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void closeBottomSheet() => super.noSuchMethod(
        Invocation.method(
          #closeBottomSheet,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void showSavingResultMessage(_i9.Future<bool?>? isSuccess) =>
      super.noSuchMethod(
        Invocation.method(
          #showSavingResultMessage,
          [isSuccess],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void createComment(
    String? text,
    bool? isAnonymous,
    _i15.OnGetUserById? getUserById,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #createComment,
          [
            text,
            isAnonymous,
            getUserById,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void deleteSuggestion() => super.noSuchMethod(
        Invocation.method(
          #deleteSuggestion,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void vote() => super.noSuchMethod(
        Invocation.method(
          #vote,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void changeNotification(bool? isNotificationOn) => super.noSuchMethod(
        Invocation.method(
          #changeNotification,
          [isNotificationOn],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void emit(_i3.SuggestionState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onChange(_i16.Change<_i3.SuggestionState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i9.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}

/// A class which mocks [SuggestionsCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockSuggestionsCubit extends _i1.Mock implements _i17.SuggestionsCubit {
  MockSuggestionsCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.SuggestionsState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeSuggestionsState_2(
          this,
          Invocation.getter(#state),
        ),
      ) as _i4.SuggestionsState);
  @override
  _i9.Stream<_i4.SuggestionsState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i9.Stream<_i4.SuggestionsState>.empty(),
      ) as _i9.Stream<_i4.SuggestionsState>);
  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);
  @override
  void init() => super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void vote(
    _i10.SuggestionStatus? status,
    int? i,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #vote,
          [
            status,
            i,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void openCreateBottomSheet() => super.noSuchMethod(
        Invocation.method(
          #openCreateBottomSheet,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void closeCreateBottomSheet() => super.noSuchMethod(
        Invocation.method(
          #closeCreateBottomSheet,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void changeActiveTab(_i10.SuggestionStatus? activeTab) => super.noSuchMethod(
        Invocation.method(
          #changeActiveTab,
          [activeTab],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void emit(_i4.SuggestionsState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onChange(_i16.Change<_i4.SuggestionsState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i9.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}

/// A class which mocks [SuggestionsDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSuggestionsDataSource extends _i1.Mock
    implements _i18.SuggestionsDataSource {
  MockSuggestionsDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get userId => (super.noSuchMethod(
        Invocation.getter(#userId),
        returnValue: '',
      ) as String);
  @override
  _i9.Future<_i2.Wrapper<List<_i10.Suggestion>>> getAllSuggestions() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllSuggestions,
          [],
        ),
        returnValue: _i9.Future<_i2.Wrapper<List<_i10.Suggestion>>>.value(
            _FakeWrapper_0<List<_i10.Suggestion>>(
          this,
          Invocation.method(
            #getAllSuggestions,
            [],
          ),
        )),
      ) as _i9.Future<_i2.Wrapper<List<_i10.Suggestion>>>);
  @override
  _i9.Future<_i2.Wrapper<_i10.Suggestion>> createSuggestion(
          _i10.CreateSuggestionModel? suggestion) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSuggestion,
          [suggestion],
        ),
        returnValue: _i9.Future<_i2.Wrapper<_i10.Suggestion>>.value(
            _FakeWrapper_0<_i10.Suggestion>(
          this,
          Invocation.method(
            #createSuggestion,
            [suggestion],
          ),
        )),
      ) as _i9.Future<_i2.Wrapper<_i10.Suggestion>>);
  @override
  _i9.Future<_i2.Wrapper<_i10.Suggestion>> getSuggestionById(
          String? suggestionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSuggestionById,
          [suggestionId],
        ),
        returnValue: _i9.Future<_i2.Wrapper<_i10.Suggestion>>.value(
            _FakeWrapper_0<_i10.Suggestion>(
          this,
          Invocation.method(
            #getSuggestionById,
            [suggestionId],
          ),
        )),
      ) as _i9.Future<_i2.Wrapper<_i10.Suggestion>>);
  @override
  _i9.Future<_i2.Wrapper<_i10.Suggestion>> updateSuggestion(
          _i10.Suggestion? suggestion) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSuggestion,
          [suggestion],
        ),
        returnValue: _i9.Future<_i2.Wrapper<_i10.Suggestion>>.value(
            _FakeWrapper_0<_i10.Suggestion>(
          this,
          Invocation.method(
            #updateSuggestion,
            [suggestion],
          ),
        )),
      ) as _i9.Future<_i2.Wrapper<_i10.Suggestion>>);
  @override
  _i9.Future<_i2.Wrapper<_i10.Suggestion>> deleteSuggestionById(
          String? suggestionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteSuggestionById,
          [suggestionId],
        ),
        returnValue: _i9.Future<_i2.Wrapper<_i10.Suggestion>>.value(
            _FakeWrapper_0<_i10.Suggestion>(
          this,
          Invocation.method(
            #deleteSuggestionById,
            [suggestionId],
          ),
        )),
      ) as _i9.Future<_i2.Wrapper<_i10.Suggestion>>);
  @override
  _i9.Future<_i2.Wrapper<void>> upvote(String? suggestionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #upvote,
          [suggestionId],
        ),
        returnValue: _i9.Future<_i2.Wrapper<void>>.value(_FakeWrapper_0<void>(
          this,
          Invocation.method(
            #upvote,
            [suggestionId],
          ),
        )),
      ) as _i9.Future<_i2.Wrapper<void>>);
  @override
  _i9.Future<_i2.Wrapper<void>> downvote(String? suggestionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #downvote,
          [suggestionId],
        ),
        returnValue: _i9.Future<_i2.Wrapper<void>>.value(_FakeWrapper_0<void>(
          this,
          Invocation.method(
            #downvote,
            [suggestionId],
          ),
        )),
      ) as _i9.Future<_i2.Wrapper<void>>);
  @override
  _i9.Future<_i2.Wrapper<void>> addNotifyToUpdateUser(String? suggestionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #addNotifyToUpdateUser,
          [suggestionId],
        ),
        returnValue: _i9.Future<_i2.Wrapper<void>>.value(_FakeWrapper_0<void>(
          this,
          Invocation.method(
            #addNotifyToUpdateUser,
            [suggestionId],
          ),
        )),
      ) as _i9.Future<_i2.Wrapper<void>>);
  @override
  _i9.Future<_i2.Wrapper<void>> deleteNotifyToUpdateUser(
          String? suggestionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteNotifyToUpdateUser,
          [suggestionId],
        ),
        returnValue: _i9.Future<_i2.Wrapper<void>>.value(_FakeWrapper_0<void>(
          this,
          Invocation.method(
            #deleteNotifyToUpdateUser,
            [suggestionId],
          ),
        )),
      ) as _i9.Future<_i2.Wrapper<void>>);
  @override
  _i9.Future<_i2.Wrapper<List<_i12.Comment>>> getAllComments(
          String? suggestionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllComments,
          [suggestionId],
        ),
        returnValue: _i9.Future<_i2.Wrapper<List<_i12.Comment>>>.value(
            _FakeWrapper_0<List<_i12.Comment>>(
          this,
          Invocation.method(
            #getAllComments,
            [suggestionId],
          ),
        )),
      ) as _i9.Future<_i2.Wrapper<List<_i12.Comment>>>);
  @override
  _i9.Future<_i2.Wrapper<_i12.Comment>> getCommentById(String? commentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCommentById,
          [commentId],
        ),
        returnValue: _i9.Future<_i2.Wrapper<_i12.Comment>>.value(
            _FakeWrapper_0<_i12.Comment>(
          this,
          Invocation.method(
            #getCommentById,
            [commentId],
          ),
        )),
      ) as _i9.Future<_i2.Wrapper<_i12.Comment>>);
  @override
  _i9.Future<_i2.Wrapper<_i12.Comment>> createComment(
          _i12.CreateCommentModel? comment) =>
      (super.noSuchMethod(
        Invocation.method(
          #createComment,
          [comment],
        ),
        returnValue: _i9.Future<_i2.Wrapper<_i12.Comment>>.value(
            _FakeWrapper_0<_i12.Comment>(
          this,
          Invocation.method(
            #createComment,
            [comment],
          ),
        )),
      ) as _i9.Future<_i2.Wrapper<_i12.Comment>>);
  @override
  _i9.Future<_i2.Wrapper<_i12.Comment>> updateComment(_i12.Comment? comment) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateComment,
          [comment],
        ),
        returnValue: _i9.Future<_i2.Wrapper<_i12.Comment>>.value(
            _FakeWrapper_0<_i12.Comment>(
          this,
          Invocation.method(
            #updateComment,
            [comment],
          ),
        )),
      ) as _i9.Future<_i2.Wrapper<_i12.Comment>>);
  @override
  _i9.Future<_i2.Wrapper<_i12.Comment>> deleteCommentById(String? commentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCommentById,
          [commentId],
        ),
        returnValue: _i9.Future<_i2.Wrapper<_i12.Comment>>.value(
            _FakeWrapper_0<_i12.Comment>(
          this,
          Invocation.method(
            #deleteCommentById,
            [commentId],
          ),
        )),
      ) as _i9.Future<_i2.Wrapper<_i12.Comment>>);
  @override
  _i9.Future<List<String>?> uploadMultiplePhotos(
          {required int? availableNumOfPhotos}) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadMultiplePhotos,
          [],
          {#availableNumOfPhotos: availableNumOfPhotos},
        ),
        returnValue: _i9.Future<List<String>?>.value(),
      ) as _i9.Future<List<String>?>);
  @override
  _i9.Future<bool?> saveToGallery(String? url) => (super.noSuchMethod(
        Invocation.method(
          #saveToGallery,
          [url],
        ),
        returnValue: _i9.Future<bool?>.value(),
      ) as _i9.Future<bool?>);
  @override
  _i9.Future<_i11.SuggestionAuthor?> getUserById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserById,
          [id],
        ),
        returnValue: _i9.Future<_i11.SuggestionAuthor?>.value(),
      ) as _i9.Future<_i11.SuggestionAuthor?>);
}

/// A class which mocks [SuggestionsTheme].
///
/// See the documentation for Mockito's code generation for more information.
class MockSuggestionsTheme extends _i1.Mock implements _i7.SuggestionsTheme {
  MockSuggestionsTheme() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Color get primaryBackgroundColor => (super.noSuchMethod(
        Invocation.getter(#primaryBackgroundColor),
        returnValue: _FakeColor_3(
          this,
          Invocation.getter(#primaryBackgroundColor),
        ),
      ) as _i5.Color);
  @override
  _i5.Color get secondaryBackgroundColor => (super.noSuchMethod(
        Invocation.getter(#secondaryBackgroundColor),
        returnValue: _FakeColor_3(
          this,
          Invocation.getter(#secondaryBackgroundColor),
        ),
      ) as _i5.Color);
  @override
  _i5.Color get thirdBackgroundColor => (super.noSuchMethod(
        Invocation.getter(#thirdBackgroundColor),
        returnValue: _FakeColor_3(
          this,
          Invocation.getter(#thirdBackgroundColor),
        ),
      ) as _i5.Color);
  @override
  _i5.Color get bottomSheetBackgroundColor => (super.noSuchMethod(
        Invocation.getter(#bottomSheetBackgroundColor),
        returnValue: _FakeColor_3(
          this,
          Invocation.getter(#bottomSheetBackgroundColor),
        ),
      ) as _i5.Color);
  @override
  String get fontFamily => (super.noSuchMethod(
        Invocation.getter(#fontFamily),
        returnValue: '',
      ) as String);
  @override
  _i5.Color get primaryTextColor => (super.noSuchMethod(
        Invocation.getter(#primaryTextColor),
        returnValue: _FakeColor_3(
          this,
          Invocation.getter(#primaryTextColor),
        ),
      ) as _i5.Color);
  @override
  _i5.Color get secondaryTextColor => (super.noSuchMethod(
        Invocation.getter(#secondaryTextColor),
        returnValue: _FakeColor_3(
          this,
          Invocation.getter(#secondaryTextColor),
        ),
      ) as _i5.Color);
  @override
  _i5.Color get primaryIconColor => (super.noSuchMethod(
        Invocation.getter(#primaryIconColor),
        returnValue: _FakeColor_3(
          this,
          Invocation.getter(#primaryIconColor),
        ),
      ) as _i5.Color);
  @override
  _i5.Color get secondaryIconColor => (super.noSuchMethod(
        Invocation.getter(#secondaryIconColor),
        returnValue: _FakeColor_3(
          this,
          Invocation.getter(#secondaryIconColor),
        ),
      ) as _i5.Color);
  @override
  _i5.Color get actionColor => (super.noSuchMethod(
        Invocation.getter(#actionColor),
        returnValue: _FakeColor_3(
          this,
          Invocation.getter(#actionColor),
        ),
      ) as _i5.Color);
  @override
  _i5.Color get actionPressedColor => (super.noSuchMethod(
        Invocation.getter(#actionPressedColor),
        returnValue: _FakeColor_3(
          this,
          Invocation.getter(#actionPressedColor),
        ),
      ) as _i5.Color);
  @override
  _i5.Color get actionBackgroundColor => (super.noSuchMethod(
        Invocation.getter(#actionBackgroundColor),
        returnValue: _FakeColor_3(
          this,
          Invocation.getter(#actionBackgroundColor),
        ),
      ) as _i5.Color);
  @override
  _i5.Color get dividerColor => (super.noSuchMethod(
        Invocation.getter(#dividerColor),
        returnValue: _FakeColor_3(
          this,
          Invocation.getter(#dividerColor),
        ),
      ) as _i5.Color);
  @override
  _i5.Color get dialogBarrierColor => (super.noSuchMethod(
        Invocation.getter(#dialogBarrierColor),
        returnValue: _FakeColor_3(
          this,
          Invocation.getter(#dialogBarrierColor),
        ),
      ) as _i5.Color);
  @override
  _i5.Color get elevatedButtonColor => (super.noSuchMethod(
        Invocation.getter(#elevatedButtonColor),
        returnValue: _FakeColor_3(
          this,
          Invocation.getter(#elevatedButtonColor),
        ),
      ) as _i5.Color);
  @override
  _i5.Color get pressedElevatedButtonColor => (super.noSuchMethod(
        Invocation.getter(#pressedElevatedButtonColor),
        returnValue: _FakeColor_3(
          this,
          Invocation.getter(#pressedElevatedButtonColor),
        ),
      ) as _i5.Color);
  @override
  _i5.Color get elevatedButtonTextColor => (super.noSuchMethod(
        Invocation.getter(#elevatedButtonTextColor),
        returnValue: _FakeColor_3(
          this,
          Invocation.getter(#elevatedButtonTextColor),
        ),
      ) as _i5.Color);
  @override
  _i5.Color get focusedTextButtonColor => (super.noSuchMethod(
        Invocation.getter(#focusedTextButtonColor),
        returnValue: _FakeColor_3(
          this,
          Invocation.getter(#focusedTextButtonColor),
        ),
      ) as _i5.Color);
  @override
  _i5.Color get focusedTextColor => (super.noSuchMethod(
        Invocation.getter(#focusedTextColor),
        returnValue: _FakeColor_3(
          this,
          Invocation.getter(#focusedTextColor),
        ),
      ) as _i5.Color);
  @override
  _i5.Color get focusedTextFieldBorderlineColor => (super.noSuchMethod(
        Invocation.getter(#focusedTextFieldBorderlineColor),
        returnValue: _FakeColor_3(
          this,
          Invocation.getter(#focusedTextFieldBorderlineColor),
        ),
      ) as _i5.Color);
  @override
  _i5.Color get focusedTonalButtonColor => (super.noSuchMethod(
        Invocation.getter(#focusedTonalButtonColor),
        returnValue: _FakeColor_3(
          this,
          Invocation.getter(#focusedTonalButtonColor),
        ),
      ) as _i5.Color);
  @override
  _i5.Color get enabledTextColor => (super.noSuchMethod(
        Invocation.getter(#enabledTextColor),
        returnValue: _FakeColor_3(
          this,
          Invocation.getter(#enabledTextColor),
        ),
      ) as _i5.Color);
  @override
  _i5.Color get disabledTextColor => (super.noSuchMethod(
        Invocation.getter(#disabledTextColor),
        returnValue: _FakeColor_3(
          this,
          Invocation.getter(#disabledTextColor),
        ),
      ) as _i5.Color);
  @override
  _i5.Color get disabledTextButtonColor => (super.noSuchMethod(
        Invocation.getter(#disabledTextButtonColor),
        returnValue: _FakeColor_3(
          this,
          Invocation.getter(#disabledTextButtonColor),
        ),
      ) as _i5.Color);
  @override
  _i5.Color get tonalButtonColor => (super.noSuchMethod(
        Invocation.getter(#tonalButtonColor),
        returnValue: _FakeColor_3(
          this,
          Invocation.getter(#tonalButtonColor),
        ),
      ) as _i5.Color);
  @override
  _i5.Color get errorColor => (super.noSuchMethod(
        Invocation.getter(#errorColor),
        returnValue: _FakeColor_3(
          this,
          Invocation.getter(#errorColor),
        ),
      ) as _i5.Color);
  @override
  _i5.Color get fade => (super.noSuchMethod(
        Invocation.getter(#fade),
        returnValue: _FakeColor_3(
          this,
          Invocation.getter(#fade),
        ),
      ) as _i5.Color);
  @override
  _i5.Color get fabColor => (super.noSuchMethod(
        Invocation.getter(#fabColor),
        returnValue: _FakeColor_3(
          this,
          Invocation.getter(#fabColor),
        ),
      ) as _i5.Color);
  @override
  _i5.Color get upvoteArrowColor => (super.noSuchMethod(
        Invocation.getter(#upvoteArrowColor),
        returnValue: _FakeColor_3(
          this,
          Invocation.getter(#upvoteArrowColor),
        ),
      ) as _i5.Color);
  @override
  _i5.Color get activatedUpvoteArrowColor => (super.noSuchMethod(
        Invocation.getter(#activatedUpvoteArrowColor),
        returnValue: _FakeColor_3(
          this,
          Invocation.getter(#activatedUpvoteArrowColor),
        ),
      ) as _i5.Color);
  @override
  _i5.Color get requestsTabColor => (super.noSuchMethod(
        Invocation.getter(#requestsTabColor),
        returnValue: _FakeColor_3(
          this,
          Invocation.getter(#requestsTabColor),
        ),
      ) as _i5.Color);
  @override
  _i5.Color get inProgressTabColor => (super.noSuchMethod(
        Invocation.getter(#inProgressTabColor),
        returnValue: _FakeColor_3(
          this,
          Invocation.getter(#inProgressTabColor),
        ),
      ) as _i5.Color);
  @override
  _i5.Color get completedTabColor => (super.noSuchMethod(
        Invocation.getter(#completedTabColor),
        returnValue: _FakeColor_3(
          this,
          Invocation.getter(#completedTabColor),
        ),
      ) as _i5.Color);
  @override
  _i5.Color get featureLabelColor => (super.noSuchMethod(
        Invocation.getter(#featureLabelColor),
        returnValue: _FakeColor_3(
          this,
          Invocation.getter(#featureLabelColor),
        ),
      ) as _i5.Color);
  @override
  _i5.Color get bugLabelColor => (super.noSuchMethod(
        Invocation.getter(#bugLabelColor),
        returnValue: _FakeColor_3(
          this,
          Invocation.getter(#bugLabelColor),
        ),
      ) as _i5.Color);
  @override
  _i6.TextStyle get base => (super.noSuchMethod(
        Invocation.getter(#base),
        returnValue: _FakeTextStyle_4(
          this,
          Invocation.getter(#base),
        ),
      ) as _i6.TextStyle);
  @override
  _i6.TextStyle get textXXL => (super.noSuchMethod(
        Invocation.getter(#textXXL),
        returnValue: _FakeTextStyle_4(
          this,
          Invocation.getter(#textXXL),
        ),
      ) as _i6.TextStyle);
  @override
  _i6.TextStyle get textL => (super.noSuchMethod(
        Invocation.getter(#textL),
        returnValue: _FakeTextStyle_4(
          this,
          Invocation.getter(#textL),
        ),
      ) as _i6.TextStyle);
  @override
  _i6.TextStyle get textM => (super.noSuchMethod(
        Invocation.getter(#textM),
        returnValue: _FakeTextStyle_4(
          this,
          Invocation.getter(#textM),
        ),
      ) as _i6.TextStyle);
  @override
  _i6.TextStyle get textMPlus => (super.noSuchMethod(
        Invocation.getter(#textMPlus),
        returnValue: _FakeTextStyle_4(
          this,
          Invocation.getter(#textMPlus),
        ),
      ) as _i6.TextStyle);
  @override
  _i6.TextStyle get textS => (super.noSuchMethod(
        Invocation.getter(#textS),
        returnValue: _FakeTextStyle_4(
          this,
          Invocation.getter(#textS),
        ),
      ) as _i6.TextStyle);
  @override
  _i6.TextStyle get textXXLBold => (super.noSuchMethod(
        Invocation.getter(#textXXLBold),
        returnValue: _FakeTextStyle_4(
          this,
          Invocation.getter(#textXXLBold),
        ),
      ) as _i6.TextStyle);
  @override
  _i6.TextStyle get textLBold => (super.noSuchMethod(
        Invocation.getter(#textLBold),
        returnValue: _FakeTextStyle_4(
          this,
          Invocation.getter(#textLBold),
        ),
      ) as _i6.TextStyle);
  @override
  _i6.TextStyle get textMSecondary => (super.noSuchMethod(
        Invocation.getter(#textMSecondary),
        returnValue: _FakeTextStyle_4(
          this,
          Invocation.getter(#textMSecondary),
        ),
      ) as _i6.TextStyle);
  @override
  _i6.TextStyle get textMPlusBold => (super.noSuchMethod(
        Invocation.getter(#textMPlusBold),
        returnValue: _FakeTextStyle_4(
          this,
          Invocation.getter(#textMPlusBold),
        ),
      ) as _i6.TextStyle);
  @override
  _i6.TextStyle get textMBold => (super.noSuchMethod(
        Invocation.getter(#textMBold),
        returnValue: _FakeTextStyle_4(
          this,
          Invocation.getter(#textMBold),
        ),
      ) as _i6.TextStyle);
  @override
  _i6.TextStyle get textMSecondaryBold => (super.noSuchMethod(
        Invocation.getter(#textMSecondaryBold),
        returnValue: _FakeTextStyle_4(
          this,
          Invocation.getter(#textMSecondaryBold),
        ),
      ) as _i6.TextStyle);
  @override
  _i7.SuggestionsTheme copyWith({
    _i5.Color? primaryBackgroundColor,
    _i5.Color? secondaryBackgroundColor,
    _i5.Color? thirdBackgroundColor,
    _i5.Color? bottomSheetBackgroundColor,
    String? fontFamily,
    _i5.Color? primaryTextColor,
    _i5.Color? secondaryTextColor,
    _i5.Color? primaryIconColor,
    _i5.Color? secondaryIconColor,
    _i5.Color? actionColor,
    _i5.Color? actionPressedColor,
    _i5.Color? actionBackgroundColor,
    _i5.Color? dividerColor,
    _i5.Color? dialogBarrierColor,
    _i5.Color? elevatedButtonColor,
    _i5.Color? pressedElevatedButtonColor,
    _i5.Color? elevatedButtonTextColor,
    _i5.Color? focusedTextButtonColor,
    _i5.Color? focusedTextColor,
    _i5.Color? focusedTextFieldBorderlineColor,
    _i5.Color? focusedTonalButtonColor,
    _i5.Color? enabledTextColor,
    _i5.Color? disabledTextColor,
    _i5.Color? disabledTextButtonColor,
    _i5.Color? tonalButtonColor,
    _i5.Color? errorColor,
    _i5.Color? upvoteArrowColor,
    _i5.Color? activatedUpvoteArrowColor,
    _i5.Color? requestsTabColor,
    _i5.Color? inProgressTabColor,
    _i5.Color? completedTabColor,
    _i5.Color? featureLabelColor,
    _i5.Color? bugLabelColor,
    _i5.Color? fade,
    _i5.Color? fabColor,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyWith,
          [],
          {
            #primaryBackgroundColor: primaryBackgroundColor,
            #secondaryBackgroundColor: secondaryBackgroundColor,
            #thirdBackgroundColor: thirdBackgroundColor,
            #bottomSheetBackgroundColor: bottomSheetBackgroundColor,
            #fontFamily: fontFamily,
            #primaryTextColor: primaryTextColor,
            #secondaryTextColor: secondaryTextColor,
            #primaryIconColor: primaryIconColor,
            #secondaryIconColor: secondaryIconColor,
            #actionColor: actionColor,
            #actionPressedColor: actionPressedColor,
            #actionBackgroundColor: actionBackgroundColor,
            #dividerColor: dividerColor,
            #dialogBarrierColor: dialogBarrierColor,
            #elevatedButtonColor: elevatedButtonColor,
            #pressedElevatedButtonColor: pressedElevatedButtonColor,
            #elevatedButtonTextColor: elevatedButtonTextColor,
            #focusedTextButtonColor: focusedTextButtonColor,
            #focusedTextColor: focusedTextColor,
            #focusedTextFieldBorderlineColor: focusedTextFieldBorderlineColor,
            #focusedTonalButtonColor: focusedTonalButtonColor,
            #enabledTextColor: enabledTextColor,
            #disabledTextColor: disabledTextColor,
            #disabledTextButtonColor: disabledTextButtonColor,
            #tonalButtonColor: tonalButtonColor,
            #errorColor: errorColor,
            #upvoteArrowColor: upvoteArrowColor,
            #activatedUpvoteArrowColor: activatedUpvoteArrowColor,
            #requestsTabColor: requestsTabColor,
            #inProgressTabColor: inProgressTabColor,
            #completedTabColor: completedTabColor,
            #featureLabelColor: featureLabelColor,
            #bugLabelColor: bugLabelColor,
            #fade: fade,
            #fabColor: fabColor,
          },
        ),
        returnValue: _FakeSuggestionsTheme_5(
          this,
          Invocation.method(
            #copyWith,
            [],
            {
              #primaryBackgroundColor: primaryBackgroundColor,
              #secondaryBackgroundColor: secondaryBackgroundColor,
              #thirdBackgroundColor: thirdBackgroundColor,
              #bottomSheetBackgroundColor: bottomSheetBackgroundColor,
              #fontFamily: fontFamily,
              #primaryTextColor: primaryTextColor,
              #secondaryTextColor: secondaryTextColor,
              #primaryIconColor: primaryIconColor,
              #secondaryIconColor: secondaryIconColor,
              #actionColor: actionColor,
              #actionPressedColor: actionPressedColor,
              #actionBackgroundColor: actionBackgroundColor,
              #dividerColor: dividerColor,
              #dialogBarrierColor: dialogBarrierColor,
              #elevatedButtonColor: elevatedButtonColor,
              #pressedElevatedButtonColor: pressedElevatedButtonColor,
              #elevatedButtonTextColor: elevatedButtonTextColor,
              #focusedTextButtonColor: focusedTextButtonColor,
              #focusedTextColor: focusedTextColor,
              #focusedTextFieldBorderlineColor: focusedTextFieldBorderlineColor,
              #focusedTonalButtonColor: focusedTonalButtonColor,
              #enabledTextColor: enabledTextColor,
              #disabledTextColor: disabledTextColor,
              #disabledTextButtonColor: disabledTextButtonColor,
              #tonalButtonColor: tonalButtonColor,
              #errorColor: errorColor,
              #upvoteArrowColor: upvoteArrowColor,
              #activatedUpvoteArrowColor: activatedUpvoteArrowColor,
              #requestsTabColor: requestsTabColor,
              #inProgressTabColor: inProgressTabColor,
              #completedTabColor: completedTabColor,
              #featureLabelColor: featureLabelColor,
              #bugLabelColor: bugLabelColor,
              #fade: fade,
              #fabColor: fabColor,
            },
          ),
        ),
      ) as _i7.SuggestionsTheme);
}
